### ISSUE TITLE
Missing / inconsistent version tags

### ISSUE THREAD

**Issue by mans0954** [leanprover-community/mathlib-tools#105]
Versions 0.04, 0.07, 0.0.8, 0.0.9 are tagged (the latter two as v0.0.8 and v0.0.9). But there is no tag for v1.0.0. Presumably [this commit](https://github.com/leanprover-community/mathlib-tools/commit/77e36fa1c84b87cea81407d5acd08389b9777790) should be tagged as v1.0.0 (although, confusingly, the Changelog says 1.0.1).

Consistent tagging is useful for tools which monitor upstream repos (e.g. [Debian watch](https://wiki.debian.org/debian/watch) ) when source tarballs are not published on GitHub.

**Comment by PatrickMassot** [comment]
Thanks. I've fixed the latest tag and changelog and I'll try to stay consistent from now on.
