### ISSUE TITLE
macOS installer should suggest install steps for M1 users

### ISSUE THREAD

**Issue by Julian** [leanprover-community/mathlib-tools#107]
Running `brew install elan` on an M1 mac (which `install_macos.sh` does) produces:

```
⊙  brew install elan-init                                                                                                                                                           julian@Airm
elan-init: The x86_64 architecture is required for this software.
Error: An unsatisfied requirement failed this build.
```

because we've marked `elan` as not supporting ARM (until/unless lean gets ARM binaries for macOS).

We likely should here emit some more specific instructions suggesting some alternate steps.

**Comment by gebner** [comment]
Do you have a proposal for alternative instructions that work on ARM?  I think that any improvement is welcome here, as long as it doesn't break amd64 or older macos versions.

**Comment by Julian** [comment]
I guess given that running this install script anyhow comes with some level of trust (and may involve installing homebrew already), I suppose making the install script install a rosetta-d homebrew install for ARM users, and then using that to install intel elan is likely reasonable behavior (and users who want more control, i.e. native binaries, will ignore the script and go compile themselves).

**Comment by PatrickMassot** [comment]
Thanks for you contribution. We are closing all pull requests and issues since this tool no longer has any relevance in the Lean 4 era. This repository will now be archived.
