### ISSUE TITLE
'leanproject new' fails with lean 4 installed

### ISSUE THREAD

**Issue by avigad** [leanprover-community/mathlib-tools#120]
If one has lean 3 and lean 4 both installed with lean 4 as the system default, the behavior of `leanproject new test` is cryptic. 

What happens is that `leanproject` calls `leanpkg new test`, but `elan` interprets that as a call to the lean 4 `leanpkg`, which does not have a `new` command.

**Comment by PatrickMassot** [comment]
This has been reported on Zulip as well, but I don't quite know what to do, except hoping that people who have Lean 4 as their default Lean know what they are doing.

**Comment by PatrickMassot** [comment]
Thanks for you contribution. We are closing all pull requests and issues since this tool no longer has any relevance in the Lean 4 era. This repository will now be archived.
