### ISSUE TITLE
`toml` to `tomli` & `tomli_w` migration

### ISSUE THREAD

**Issue by xgqt** [leanprover-community/mathlib-tools#130]
Citing Michał Górny's comment on the Gentoo bugtracker (https://bugs.gentoo.org/878651):
"""
dev-python/toml has had its last release in 2020.  It doesn't implement TOML 1.0 and it is buggy.  With Python 3.11, we have a built-in tomllib module to handle reading TOML, and in general tomli/tomli-w pair to handle load/dump everywhere.

Useful resources:

https://projects.gentoo.org/python/guide/porting.html#replacing-the-toml-package
https://fedoraproject.org/wiki/Changes/DeprecatePythonToml
"""

I would like to begin work on this issue and submit a PR, but I also would like to have a confirmation this upstream wants to migrate away from the `toml` Python package.

**Comment by jcommelin** [comment]
As far as I understand, Lean 4 will no longer use toml files. Since we are currently migrating to Lean 4, I don't think it's worth the effort to work on this issue.

**Comment by xgqt** [comment]
So lean 3 support will be totally dropped? I see no reason to suddenly remove this compatibility.
I myself still use lean 3 as 4 is unstable and havent had a proper release.

**Comment by jcommelin** [comment]
We're using extremely minimalist toml files. We haven't had any bug reports related to toml. So from my perspective transitioning it is not worth any effort to transition to tomli.

**Comment by xgqt** [comment]
> We haven't had any bug reports related to toml.

But that does not mean they do not exist for the `toml` library (see: https://github.com/uiri/toml/issues).

Please read the Fedora's report (https://fedoraproject.org/wiki/Changes/DeprecatePythonToml#Detailed_Description) on the subject if you haven't.

**Comment by PatrickMassot** [comment]
Thanks for you contribution. We are closing all pull requests and issues since this tool no longer has any relevance in the Lean 4 era. This repository will now be archived.
