### ISSUE TITLE
`leanproject up` should call `leanpkg configure`

### ISSUE THREAD

**Issue by gebner** [leanprover-community/mathlib-tools#22]
It's easy to forget to call `leanpkg configure` if you're cloning mathlib and then run `leanproject up`.

**Comment by PatrickMassot** [comment]
I don't understand what you hope `leanpkg configure` would do for you. I agree we should have a special treatment for `leanproject get mathlib` (and allow to choose a branch), but you can already `git clone` of `leanproject get` mathlib, checkout the `lean-3.6.1` branch and run `leanproject up` or `leanproject get-cache` to get oleans without ever using  `leanpkg`.

**Comment by gebner** [comment]
If you don't run `leanpkg configure` then you get errors like "file 'data/nat/basic' not found the in LEAN_PATH".  You'll have oleans but can't run lean or vscode.

**Comment by PatrickMassot** [comment]
Ok I understand. If you `git clone` by hand and get cache then indeed you won't have `leanpkg.path` configured. It only proves using `git clone` by hand is breaks the `leanproject` workflow. I'm a bit reluctant to keep adding complexity to `leanproject` only to support more ways to misuse it. But I still "fixed" this "issue" in c3c9c3b.
