### ISSUE TITLE
`leanproject get` should use SSH authentication if possible

### ISSUE THREAD

**Issue by gebner** [leanprover-community/mathlib-tools#25]
Currently `leanproject get foo` uses the `https` connection for the github remote.  This makes it hard to contribute.
```
leanproject get mathlib:some-branch
cd mathlib
git push
```
The last `git push` will then fail because `git` will push to `https://github.com/....`.  The http url does not work if you have two-factor authentication enabled (I have to enable it since it is required by another project).  The same issue also exists for non-mathlib projects, I've just chosen mathlib as an example.

It would be nice if `leanproject` could use the SSH url instead, if possible.

**Comment by PatrickMassot** [comment]
Fixed in d145970.
