### ISSUE TITLE
Making Lean project a git submodule of another git repo

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover-community/mathlib-tools#37]
It would be lovely if instructions could be given for accomplishing this task. We want a lean project that we're developing, which uses mathlib, to be a git subproject of a larger git repo that we're developing. We want to be able to update lean and mathlib using these tools, while pushing changes to our own code to our own repo.

**Comment by semorrison** [comment]
I do this all the time. I just `git submodule add` the project, and then
use leanproject inside that directory as usual.

**Comment by PatrickMassot** [comment]
Thanks for you contribution. We are closing all pull requests and issues since this tool no longer has any relevance in the Lean 4 era. This repository will now be archived.
