### ISSUE TITLE
`leanproject get` could create branches as well

### ISSUE THREAD

**Issue by gebner** [leanprover-community/mathlib-tools#40]
I would really like `leanproject get` to be able to create new branches like this:
```shell
leanproject get mathlib:new_branch_name
cd mathlib_new_branch_name
# start working
```

Should this be another command?  I can implement and PR this myself if you prefer, but I'd like to hear your thoughts first.

**Comment by PatrickMassot** [comment]
I understand the request, and anything that help working on mathlib is welcome. But I'm afraid the proposed interface would be very confusing if you want an existing branch but make a typo in the branch name. So I'd say we need another command.

**Comment by jcommelin** [comment]
Maybe it could be part of `leanproject new`?

**Comment by gebner** [comment]
I don't think it would fit well under `leanproject new`.  The semantics of the `new` command is to create an empty project, which doesn't apply at all to the command I am proposing.

My preferred interface would be a flag to `leanproject get`, since I essentially want `leanproject get` + `git checkout -b branch`.  (The value of integrating the combination in `leanproject` is that it automatically picks a reasonable directory name.)
```shell
leanproject get --new-branch mathlib:new_branch_name
# or
leanproject get -b mathlib:new_branch_name
```

**Comment by PatrickMassot** [comment]
Yes, I think this would avoid the issue I mentioned. Feel free to PR!
