### ISSUE TITLE
`leanproject` fails if the Lean project directory is not a Git repository

### ISSUE THREAD

**Issue by JLimperg** [leanprover-community/mathlib-tools#42]
There are two related error cases:

- When trying to build a Lean project that is not part of a Git repository, `leanproject` fails with `Invalid git repository`.

- When trying to build a Lean project in a *subfolder* of a Git repository, `leanproject` fails with `Missing leanpkg.toml`. The `--debug` output indicates that it looks for `leanpkg.toml` in the Git repository's root directory.

To reproduce the first issue:

```
$ leanproject new test
$ cd test
$ rm -r .git
$ leanproject build
```

To reproduce the second issue:

```
$ mkdir repo
$ cd repo
$ git init
$ leanproject new test
$ cd test
$ rm -r .git
$ leanproject build
```

Tested with mathlibtools-0.0.5.

**Comment by PatrickMassot** [comment]
This is not a bug, this is the intended behavior. Changing this has very low priority for me, but you can open a PR.

**Comment by JLimperg** [comment]
Fair enough! I'll take a look.

**Comment by lacker** [comment]
It would be nice if this could just look in the current directory if leanpkg.toml was not found at the git root. The current behavior makes it inconvenient to have e.g. a project that uses multiple programming languages for different components of it.

**Comment by PatrickMassot** [comment]
This was changed a while ago.
