### ISSUE TITLE
Installing with asdf python

### ISSUE THREAD

**Issue by ben-dyer** [leanprover-community/mathlib-tools#44]
After running `pip install mathlibtools` in an [asdf](https://github.com/asdf-vm/asdf) based installation of python ([plugin](https://github.com/danhper/asdf-python)), `leanproject` is not available:

```
$ leanproject
leanproject: command not found
```

I guess the binary gets added to somewhere outside of PATH, but didn't have time to track it down. 

Installed in a virtual-env instead, e.g.

```
cd my_project
python -m venv venv
source venv/bin/activate

pip install mathlibtools

leanproject new
```

**Comment by PatrickMassot** [comment]
I'm sorry but this 100% outside of this project. We use the most standard recommended way to declare script: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point I'm afraid we can't support exotic broken setups. We already have enough to do with [common broken setups](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820856) (also [here](https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1588562), and I don't even talk about globally broken setups like using Windows).

**Comment by ben-dyer** [comment]
@PatrickMassot Thanks a lot for the reply and the links, seems the asdf plugin I was using is not supporting console scripts
