### ISSUE TITLE
look for xz archives first on Azure

### ISSUE THREAD

**Issue by robertylewis** [leanprover-community/mathlib-tools#48]
We're now pushing xz archives to Azure alongside the gz ones: https://github.com/leanprover-community/mathlib/pull/2719

These should be preferred by leanproject when available. To make the transition easier, we'll keep uploading both for a while.

I guess the relevant function is https://github.com/leanprover-community/mathlib-tools/blob/master/mathlibtools/lib.py#L141 but I'm not sure how modularized this is. I can add a few lines there and @PatrickMassot can tell me what I'm missing, or he can do it himself, either way!

**Comment by PatrickMassot** [comment]
Yes, this is the relevant function. I don't think there is anything hidden here. You only need to pay attention to the subtlety that files are both searched in the local cache (unless the `--force-downlad` option was used) and then downloaded if needed. I think you can do the modification, but I'll do it when I'll find time if you don't.

**Comment by bryangingechen** [comment]
This was fixed in #50.
