### ISSUE TITLE
Mathlib build but not in the LEAN_PATH afterward [Windows]

### ISSUE THREAD

**Issue by dbonattoj** [leanprover-community/mathlib-tools#49]
Hi!

I was trying to play with [logical verification 2019](https://github.com/blanchette/logical_verification_2019/), however I ran into [issues](https://github.com/blanchette/logical_verification_2019/issues/1) during the build process of Mathlib.

Trying to pinpoint the problem and reproduce it, I realized that I cannot even generate the **tutorial**:

```
$ leanproject get tutorials
Cloning from git@github.com:leanprover-community/tutorials.git
configuring tuto 0.1
WARNING: leanpkg configurations not specifying `path = "src"` are deprecated.
mathlib: cloning https://github.com/leanprover-community/mathlib to _target/deps/mathlib
> git clone https://github.com/leanprover-community/mathlib _target/deps/mathlib
Cloning into '_target/deps/mathlib'...
remote: Enumerating objects: 182, done.
remote: Counting objects: 100% (182/182), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 48871 (delta 93), reused 87 (delta 44), pack-reused 48689
Receiving objects: 100% (48871/48871), 20.76 MiB | 2.76 MiB/s, done.
Resolving deltas: 100% (37626/37626), done.
> git checkout --detach 3710744b411550474ecf27d3c50d92156b5ffc95    # in directory _target/deps/mathlib
HEAD is now at 3710744b feat(meta/uchange): universe lifting and lowering in meta (#2627)
Looking for local mathlib oleans
Found local mathlib oleans
```

Then I ran into https://github.com/leanprover-community/mathlib-tools/issues/46
```
$ cd tutorials
$ leanproject.exe up
[WinError 5] Access is denied: 'D:\\dev\\tmp\\tmp\\tutorials\\_target\\deps\\mathlib\\.git\\objects\\pack\\pack-7f4d731199a466a78ed1f930bd4d4b140a20c980.idx'
```

If instead of doing `leanproject.exe up`, I do:
```
rm -vfr tutorials
leanproject get tutorials
cd tutorials
leanproject.exe build 
```

The command outputs something like:
```
Building project tuto
configuring tuto 0.1
WARNING: leanpkg configurations not specifying `path = "src"` are deprecated.
mathlib: trying to update _target/deps/mathlib to revision 3710744b411550474ecf27d3c50d92156b5ffc95
> git checkout --detach 3710744b411550474ecf27d3c50d92156b5ffc95    # in directory _target/deps/mathlib
M	src/algebra/archimedean.lean
M	src/algebra/associated.lean
M	src/algebra/big_operators.lean
[...]
M	src/topology/uniform_space/separation.lean
M	src/topology/uniform_space/uniform_convergence.lean
M	src/topology/uniform_space/uniform_embedding.lean
HEAD is now at 3710744b feat(meta/uchange): universe lifting and lowering in meta (#2627)
> lean --make src/solutions
upper_bounds : set ?M_1 → set ?M_1
Try this: exact le_max_left (u N - x) (-(u N - x))
Try this: exact one_div_pos_of_pos this
```

Mathlib seems to build properly!
But then, in Visual Studio Code, all the "Solution" files have import errors for Mathlib, typically:

```
import data.real.basic
file 'data\real\basic' not found in the LEAN_PATH
```

If I try to build mathlib by hands, it seems to work:
```
$ cd _target/deps/mathlib/
$ leanpkg.exe upgrade
configuring mathlib 0.1

$ leanpkg.exe build
configuring mathlib 0.1
> lean --make src
```

OS: Windows 10
Terminal: Git Bash
VSCode is configured to use Git Bash as terminal
```"terminal.external.windowsExec": "D:\\Program Files\\Git\\git-bash.exe",```
VSCode has proper paths to lean
```
$ lean --version
Lean (version 3.11.0, commit fb3f3e88be8a, Release)
```

If I write at the first line of a solution file `#eval 1+1`, the goal says `2`, so I assume VS find Lean properly.

If needed, I can test on a Linux machine, however, I will not be able to do all my projects on Linux.

**Comment by jcommelin** [comment]
@dbonattoj Did you properly open the tutorials folder as a "VScode project"? If not, I hope that solves your problem. If you did, then I don't know an immediate solution. Maybe we can debug it over at https://leanprover.zulipchat.com/

**Comment by dbonattoj** [comment]
Thanks!! It seems to work normally by opening a folder instead of appending a folder to the current workspace, but I don't get why..

![vscode01](https://user-images.githubusercontent.com/28501597/82220500-02e7c100-991f-11ea-9635-a9810e20d703.png)

Usually, I open several folders in the same workspace without any issues (python projects), Here, I had 2-3 lean projects opened at the same time in the workspace using "file>Add Folder to Workspace"

![image](https://user-images.githubusercontent.com/28501597/82221201-f748ca00-991f-11ea-9857-753df0726fa7.png)

Complete procedure:
```
leanproject get tutorials
cd tutorials
leanproject.exe build 
```
Open an empty VS Code and reach the menu "Open Folder".

**Comment by bryangingechen** [comment]
I don't think we have support for multiple directories in a workspace in the [vscode-lean extension](https://github.com/leanprover/vscode-lean) right now.
