### ISSUE TITLE
access denied in update-mathlib

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover-community/mathlib-tools#5]
I was troubleshooting `update-mathlib` for someone else, because they got an error when extracting the compiled files. It turned out that the `tar.gz` file had a (plain text) message containing "Access Denied", and also something to do with timeout.

Presumably when downloading the files, the website timed out (maybe due to losing internet for a while), and this error message was written to the `tar.gz` file.

This error message should not be written to the `tar.gz` file, because when running `update-mathlib` again, the code will just use this corrupted file instead of trying to download again.

**Comment by cipher1024** [comment]
Github has a limit on how many anonymous requests you can make per hour. If you give setup your credentials with git (`git config --add github.user <my-user-name>` and `git config --add github.password <my-password>`) then you no longer hit that limit

**Comment by jcommelin** [comment]
Nevertheless, it seems like a good idea to avoid creating a `.tar.gz` if there was an error, as Floris explains in his last §.

**Comment by cipher1024** [comment]
@fpvandoorn did `update-mathlib` give an error message before trying to decompress the archive?

**Comment by fpvandoorn** [comment]
No, the output was as expected. From memory it was something like:

[...]
downloading binaries...
extracting binaries...
Error when opening file, giving an error message in (one of the) last lines in `update-mathlib` and some error by a basic library file called `tar.py` or something.

**Comment by gebner** [comment]
Ok, `update-mathlib` no longer exists.  `leanproject` now uses our azure cdn so github api limits no longer apply
