### ISSUE TITLE
permissions problems with `leanproject up` on Windows

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/mathlib-tools#55]
On Windows, running `leanproject up` on a Lean package that was created with `leanpkg` (not `leanproject`) may result in a permission error like the following:
```
[WinError 5] Access is denied: 'C:\\path\\to\\some_lean_project\\_target\\deps\\mathlib\\.git\\objects\\XX\\some_long_hash'
```

The solution is to delete the `_target` folder and then retry `leanproject up`.

See [this Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/DVRs/near/200087007).

**Comment by PatrickMassot** [comment]
Using Windows and mixing stuff with `leanpkg` is really insisting on having trouble. Is this still a problem with master?

**Comment by bryangingechen** [comment]
Good question. I'll try this out (hopefully by the weekend) and report back.

**Comment by bryangingechen** [comment]
I haven't had a chance to test this, but I don't think anyone else has complained about this in a while, so I'll close.
