### ISSUE TITLE
Interrupting download leaves corrupted archive behind

### ISSUE THREAD

**Issue by gebner** [leanprover-community/mathlib-tools#57]
1. `leanproject up`
2. ctrl+c while it is downloading
3. `leanproject up`
4. Error message: `Aborted!`

**Comment by eric-wieser** [comment]
I think this was fixed by @Vierkantor in #104, which says:

> I have successfully tested the changes on my Linux computer by running `leanproject get-cache` and interrupting the download, then running `leanproject get-cache` again and verifying the oleans are available. 

Feel free to reopen if you disagree.
