### ISSUE TITLE
Execute permission on cache-olean

### ISSUE THREAD

**Issue by PatrickMassot** [leanprover-community/mathlib-tools#6]
Doing a fresh `curl https://raw.githubusercontent.com/leanprover-community/mathlib-tools/master/scripts/remote-install-update-mathlib.sh -sSf | bash` gives me a working `update-mathlib` but `cache-olean` and `setup-lean-git-hooks` both lack the `x` permission. Of course I can add this to the install script but I'd prefer to understand where the difference comes from.

**Comment by cipher1024** [comment]
I feel like we never actually had that as our setup for some reason. Or maybe not uniformly

**Comment by cipher1024** [comment]
I think before, you might have installed the scripts with `setup-dev-scripts` (which does the `chmod`) but now, the remote install, also copies the files but I must have forgotten to add the `chmod` for those.

**Comment by gebner** [comment]
Closing since this installation method no longer exists after #12.
