### ISSUE TITLE
leanproject get-mathlib-cache doesn't tidy up after itself

### ISSUE THREAD

**Issue by kbuzzard** [leanprover-community/mathlib-tools#70]
The easiest way to explain the issue is to show the problem "backwards". 

```
leanproject get ImperialCollegeLondon/real-number-game
cd real-number-game
git checkout 351e7a41d24413ef1325be3bfa23805af2c42da4
leanproject get-mathlib-cache
lean --make src
```

produces a gazillion errors, the first one of which is

```
/home/buzzard/test/real-number-game/_target/deps/mathlib/src/algebra/big_operators.lean:1:0: error: ambiguous import, it can be '/home/buzzard/test/real-number-game/_target/deps/mathlib/src/data/finset/default.lean' or '/home/buzzard/test/real-number-game/_target/deps/mathlib/src/data/finset.lean'
```

Commit 351e7a41d24413ef1325be3bfa23805af2c42da4 of the real number game used a previous version of mathlib, namely mathlib commit 26918a05936335a46944c7a1fadeefcdb7224f97, where there was `src/data/finset.lean`. Current mathlib master has `src/data/finset/basic.lean`. `leanproject get-mathlib-cache` doesn't sort this out, and the import becomes ambiguous.

Why does this matter? Of course nobody does what I did above in practice. But here is what people do do; this is harder for me to demonstrate so I'll just describe what happens.

1) Me and collaborators work on real number game.
2) I decide to bump mathlib, so I do `leanproject up`, fix errors, and push.
3) Time passes, and mathlib moves on
4) A collaborator pulls RNG, and notices that leanpkg.toml has changed.
5) My collaborator types `leanproject get-mathlib-cache` -- they can't type `leanproject up` because mathlib master has moved.
6) My collaborator gets ambiguous import errors.

After `leanproject get-mathlib-cache` they will have `finset.lean` and `finset/basic.lean` in their `_target/deps/mathlib` (or possibly the oleans -- I can't remember -- but it is not the same as my `_target/deps/mathlib`. One fix is https://xkcd.com/1597/ (delete the project and then `leanproject get` again). All other fixes involve not using `leanproject`, and not using the VS Code interface to git/github either.

**Comment by PatrickMassot** [comment]
Thanks Kevin. Note that you should never use `lean --make src`. This is badly bypassing `leanproject`, you cannot hope to live in peace with `leanproject` after doing that. Using `leanproject build` would at least have given you a clear error message long before trying to compile anything. Hopefully this is now all fixed if you upgrade your mathlib tools (and **`leanproject build`**).
