### ISSUE TITLE
leanproject hooks scripts are out of date

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/mathlib-tools#73]
The edits to the `post-checkout` hook that @semorrison made in #71 aren't included in 0.0.9. 

You can confirm this by downloading and untarring `mathlibtools-0.0.9.tar.gz` [on pypi](https://pypi.org/project/mathlibtools/#files), and noticing that the `post-checkout` script there is an old version which doesn't match [the one currently in the `mathlib-tools` repo](https://github.com/leanprover-community/mathlib-tools/blob/bf53aa4268452fbfbfd48e519ef847cae7e0053c/mathlibtools/post-checkout).

Reported on [zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/leanproject.20hooks/near/204337237), but I think the timing of the message was bad.

**Comment by PatrickMassot** [comment]
I messed up when releasing 0.0.9 but I thought I fixed it in a version 0.0.9b. But maybe pip doesn't like this weird version number and his not fetching it. I'll try to release a 0.0.10 soon. Or maybe I should get rid of the stupid 0.0.* series since this is no longer an experimental tool.

**Comment by PatrickMassot** [comment]
Should be fixed in 0.0.10
