### ISSUE TITLE
refactoring directory structure of mathlib can cause problems

### ISSUE THREAD

**Issue by kbuzzard** [leanprover-community/mathlib-tools#75]
Right now I can break my project-with-mathlib-as-a-dependency using leanproject:
In version 0.0.10:
```
$ leanproject get ImperialCollegeLondon/group-theory-game
...
Looking for local mathlib oleans
Found local mathlib oleans
$ cd group-theory-game
$ lean --make src/group/definitions.lean ## works fine. Note that master mathlib dependency is after the ring change.
$ git checkout Sylow_theorems ## branch from before the recent ring -> ring/basic mathlib change
$ leanproject get-mathlib-cache
Looking for local mathlib oleans
Found local mathlib oleans
$ lean --make src/group/definitions.lean
/home/buzzard/temp/group-theory-game/_target/deps/mathlib/src/algebra/field.lean:1:0: error: ambiguous import, it can be '/home/buzzard/temp/group-theory-game/_target/deps/mathlib/src/algebra/ring/default.lean' or '/home/buzzard/temp/group-theory-game/_target/deps/mathlib/src/algebra/ring.lean'
...
```

In the last few weeks, `algebra/ring.lean` was changed to `algebra/ring/basic.lean` in mathlib, but after `leanproject get-mathlib-cache` I have in `_target` copies of both `ring.lean` and `ring/basic.lean` and this leads to ambiguous imports in mathlib later down the line.

**Comment by PatrickMassot** [comment]
Thanks for you contribution. We are closing all pull requests and issues since this tool no longer has any relevance in the Lean 4 era. This repository will now be archived.
