### ISSUE TITLE
mathlib get-cache and similar should support fetching at specified hash

### ISSUE THREAD

**Issue by pechersky** [leanprover-community/mathlib-tools#77]
As discussed in https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/get-mathlib-at-commit

Ideally, specifying a branch name, commit, or PR # in mathlib would update the mathlib dep to that target: do the git operations in the subfolder, fetch the oleans, and update the toml. If specifying a branch name where the top of the branch doesn't have oleans, optionally fall back to the latest commit that does, fetch that, and then git checkout the commit to which the branch points to. Similarly, maybe that is also valid for a target commit when specified by a hash.

**Comment by PatrickMassot** [comment]
Added in ae9119ced054eb6bec43893b73f832268e495747
