### ISSUE TITLE
`elan` is not on $PATH in gnome-terminal

### ISSUE THREAD

**Issue by Vierkantor** [leanprover-community/mathlib-tools#83]
I'm trying out the [fast installation instructions](https://leanprover-community.github.io/install/debian.html), running `install-debian.sh` on a mostly clean Ubuntu 18.04 installation. After running the installation script, VS Code, `elan` and `lean` are all available. However, when I open a new terminal, `elan` and `lean` are not on the PATH.

It seems that the cause is that `elan` is added to the PATH in `.profile` only, and `gnome-terminal` opens [an interactive, non-login shell](https://askubuntu.com/a/132319), so it will only source `.bashrc`, not `.profile`. (And the default `.bashrc` on Ubuntu doesn't source `.profile`.) I think the correct solution is to add `elan` to the PATH both in `.profile` and in `.bashrc`, this is also what `pipx` does with its PATH.

**Comment by Vierkantor** [comment]
Update: VS Code is able to run Lean, so it's just gnome-terminal that is doing something weird here.

**Comment by PatrickMassot** [comment]
Thanks for you contribution. We are closing all pull requests and issues since this tool no longer has any relevance in the Lean 4 era. This repository will now be archived.
