### ISSUE TITLE
why are we still talking about branch 'lean-3.4.2'?

### ISSUE THREAD

**Issue by kbuzzard** [leanprover-community/mathlib-tools#91]
I just wrote `leanproject new blah` and at some point during the installation procedure I noticed that it checked out a branch called `lean-3.4.2`. That is, at best, confusing. Is there no way we can switch it off? I'd rather it checked out some fancy-sounding 3.23 branch, if I'm a nervous first time user.

**Comment by jcommelin** [comment]
I guess `leanproject` can choose to put anything it likes in the `.toml`.
The current behaviour is probably whatever `elan` and `leanpkg` default to.

**Comment by robertylewis** [comment]
Yes, you should be able to set the default version for `elan` using `elan default`. (`elan toolchain list` will tell you what you have installed.) IIRC a fresh `leanproject` updates the default to the latest community Lean.

**Comment by PatrickMassot** [comment]
Thanks for you contribution. We are closing all pull requests and issues since this tool no longer has any relevance in the Lean 4 era. This repository will now be archived.
